### ISSUE TITLE
Mettre les élus en commit authors

### ISSUE THREAD

**Issue by Phyks** [Legilibre/Archeo-Lex#1]
Salut,

Je ne sais pas exactement comment ça se passe et à quelles métadonnées on a accès, mais peut être qu'il serait possible de remplacer "Le législateur" comme auteur de commit par un auteur représentatif des personnes qui ont promulguées la loi ?

En particulier, mettre l'information sur les votants quelque part (si cela a un sens), ou les élus présents à la séance du vote (en croisant avec des données de regards citoyens par exemple).

**Comment by Seb35** [comment]
Salut et merci du commentaire !

Dans l’idée, pourquoi pas mettre ça dans un commentaire de commit. Toutefois, au sens strict, ce sont les lois modificatrices qui sont promulguées, pas les codes eux-mêmes. Donc par rapport à Archéo Lex, il faudrait plutôt faire des commits correspondants à des lois modificatrices plutôt qu’à des brutes dates d’entrée en vigueur (j’ouvrirai une issue pour ça).

Ensuite, en pratique, la base LEGI (la base officielle en open data) n’a pas cette information mais il est possible que ça soit dans les données open data du [Sénat](http://data.senat.fr), ou de l’Assemblée nationale mais je ne sais pas si cette dernière fait de l’open data.

Cette idée pourrait aussi (et même mieux) s’appliquer sur La Fabrique de la Loi en mettant en commentaire de commit qui était présent et a voté ou changé quoi sur chaque amendement dans l’hémicycle ou en commission. Un exemple sur la Fabrique de la Loi : http://git.lafabriquedelaloi.fr/parlement/pjl12-349/commit/fb05bec10755d9e10f195efe012a30c67c1ccc79

**Comment by Phyks** [comment]
Merci pour ta réponse :) 

Tu aurais plus d'infos sur la Fabrique de la loi et en quoi ça diffère (ou ressemble) à Archeo-lex ?

Et tu aurais des liens vers les open data disponibles ?

J'essayerai de jeter un œil au code plus en détails quand j'aurais 5 minutes, je trouve l'idée vraiment sympa :)

**Comment by Seb35** [comment]
On s’éloigne un peu de l’issue initiale, mais bon. Et si tu veux discuter de façon générale, il y a des [listes de discussion](https://archeo-lex.fr/listes) depuis peu.

La principale différence avec La Fabrique de la Loi est que celle-ci est sur les amendements alors que Archéo Lex est sur la loi finale (et plus exactement les codes). Une autre différence est que AL est un programme de back-end (création de dépôts Git) alors que LFDLL comprend ce back-end + la visualisation (elle est pas mal d’ailleurs je trouve). J’avais rencontré Regards Citoyens en septembre 2014 pour parler AL/LFDLL/loi ouverte (un soir dans un bar) mais on n’a pour l’instant pas été plus loin ; mais il y aurait largement de quoi mutualiser tous ces projets libres (je réfléchis à une bibliothèque libre de traitement de la loi mais c’est au stade de projet et il serait préférable que j’en discute avec RC, cf [ce message sur la liste de discussion](https://archeo-lex.fr/listes/arc/discussions/2015-03/msg00000.html)).

Open data :
- https://www.etalab.gouv.fr/les-bases-legi-kali-et-circulaires-sont-disponibles-en-open-data-sur-data-gouv-fr-sous-licence-ouverte
- http://rip.journal-officiel.gouv.fr/index.php/pages/juridiques
- https://github.com/Seb35/Archeo-Lex/wiki/Base_LEGI (tutorial base LEGI)

You’re welcome :)

**Comment by Phyks** [comment]
Merci pour toutes les infos, je me suis abonné à la ML. Ça sera sûrement mieux d'en discuter là-bas.

Je suis tombé sur http://stackoverflow.com/questions/7442112/attributing-a-single-commit-to-multiple-developers aussi, qui donne quelques pistes, et dit notamment que Bazaar peut gérer plusieurs auteurs de commit.

**Comment by Seb35** [comment]
Pour répondre un peu plus précisément à la question initiale, la [base Ameli](http://data.senat.fr/ameli/) du [Sénat](http://data.senat.fr) comprend ce type d’information pour chaque amendement.

**Comment by Seb35** [comment]
Je mets le tag wontfix (=cette issue ne sera pas corrigée) car stricto sensu les lois qui sont promulguées le sont par l’Assemblée, le Sénat et le Président (et d’autres acteurs institutionnels, le Gouvernement ?), et ce ne sont pas les rédacteurs individuels (députés, sénateurs, Gouvernement pour la rédaction initiale des projets de loi) qui portent seuls la paternité morale/politique/rédactionnelle de tel ou tel partie du texte finalement adopté. Je ne pense pas qu’on puisse mettre quelque chose de réellement plus pertinent que Législateur (ou Constituant :-) dans le champ auteur.

Cela n’enlève rien aux intéressantes suggestions discutées plus haut, mais à mon sens cela devrait être traité par d’autres projets/études/sites d’information :
* les amendements ont une paternité/maternité plus identifiable, mais cela se ferait plutôt dans un projet plus amont qu’Archéo Lex qui s’attacherait par exemple à créer des dépôts Git par amendement (ce que pourrait faire [La Fabrique de la Loi](https://www.lafabriquedelaloi.fr/) et/ou [SedLex](https://github.com/Legilibre/SedLex))
* des études des votants sur tel amendement, tel article, tel texte, avec le postulat (à débattre toutefois) que les votants ont plus de "paternité/maternité politique" que les non-votants

**Comment by Seb35** [comment]
Par rapport aux liens donnés ci-dessus, on trouve également http://data.assemblee-nationale.fr avec notamment les amendements de la XVe législature qui sont en Open Data.
