### ISSUE TITLE
Manquement de paragraphes dû aux versionnage de sections

### ISSUE THREAD

**Issue by tianyikillua** [Legilibre/Archeo-Lex#11]
Parfois le fichier obtenu manque quelques paragraphes dans certaines sections : cela vient du fait que les modifications chronologiques des sections deviennent trop complexes...

```
LEGISCT1 -> Chapitre I ancien
LEGISCT2 -> Chapitre I nouveau
LEGISCT3 -> Section 1, dont le id_parent est LEGISCT1, mais en vigueur dans la nouvelle version
```

Dans cette configuration, `Section 1` disparaît dans la nouvelle version.

Je n'ai pas encore tout à fait compris votre base de données, mais le *workaround* que j'ai trouvé, au lieu de faire

```
articles_section = articles.select().where(Article.version_section == version_section_parente)
```

est de prendre maintenant toutes les possibilités

```
articles_section = articles.select().where( (Article.version_section == version_section_parente.cid.cid) | (Article.version_section == version_section_parente))
```

Idem pour les sections, dans le fichier `exporter.py`.

**Comment by Seb35** [comment]
La situation est beaucoup améliorée depuis le commit 367d633, cela corrige les exemples du "Chapitre III : La carte de séjour temporaire et la carte de séjour pluriannuelle" du CESEDA (qui était vide), la section "Chapitre VII : Sanctions prononcées par la formation restreinte de la Commission nationale de l'informatique et des libertés." de la loi 78-17 (qui était vide) et certains cas où le texte du CPI n’était nullement modifié d’une version à l’autre.

Il reste toutefois 3 versions du CPI où le texte n’est pas modifié n’est pas modifié d’une version à l’autre, ce qui n’est pas normal (2008-06-29, 2011-05-29, 2017-12-22).

**Comment by Seb35** [comment]
Bon, sur les trois versions manquantes du CPI
* deux sont normales (2008-06-29, 2017-12-22) car ce ne sont des articles morts-nés (entrée en vigueur future, mais ils ont été abrogés avant même leur entrée en vigueur)
* pour 2011-05-29, il s’agit d’une erreur dans la base LEGI également présente sur Légifrance, et ce n’est donc pas une erreur dans Archéo Lex ou legi.py - voir le détail sur https://github.com/Legilibre/legi.py/issues/40

Je ferme ce bug puisque je ne constate plus de problème. Si d’autres problèmes similaires sont trouvés, il vaudrait mieux ouvrir un nouveau bug. Dans ce cas, décrire précisément le problème (noms du code, de la section, de l’article, date à laquelle ça arrive).
