### ISSUE TITLE
Du nouveau ?

### ISSUE THREAD

**Issue by difuse** [Legilibre/Archeo-Lex#3]
Hello,

J'essaie tant bien que mal de faire fonctionner le script, dont le résultat correspond parfaitement à mes besoins (.md de codes entiers versionnés) mais je suis malheureusement novice en Python.. Et le debug est loin d'être simple, j'ai l'impression que le repo n'est pas à jour et ne peut pas fonctionner "en l'état", les tables "livraisons" ne sont pas créées.

Le projet est-il abandonné ? Possible d'avoir une petite update ou coup de pouce pour pouvoir juste mouliner mes md versionnés ?
Les nombreux projets sur ce sujet sont tous tombés en désuétude.. (Steeve) dommage !

Actuellement, j'en suis là  (J'ai ajouté manuellement les tables de livraisons à la base Sqlite) : 
![capture d ecran 2016-07-27 a 20 29 05](https://cloud.githubusercontent.com/assets/2736323/17187254/cffacd20-5438-11e6-871b-bc3a6566716f.png)

**Comment by hugoroy** [comment]
Bonjour,

Cela a-t-il fonctionné ? Pour ma part je n'arrive pas du tout à lancer le programme, même pour afficher l'aide.

```
1 hugo@xps ~/Documents/legifrance/outils/Archeo-Lex (git)-[master] % ./archeo-lex --aide                                                                                                 :(
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/peewee.py", line 3586, in connect
    **self.connect_kwargs)
  File "/usr/lib/python3.5/site-packages/peewee.py", line 3855, in _connect
    conn = sqlite3.connect(database, **kwargs)
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./archeo-lex", line 21, in <module>
    from marcheolex.basededonnees import initialisation_bdd
  File "/home/hugo/Documents/legifrance/outils/Archeo-Lex/marcheolex/basededonnees.py", line 34, in <module>
    bd.connect()
  File "/usr/lib/python3.5/site-packages/peewee.py", line 3588, in connect
    self.initialize_connection(self._local.conn)
  File "/usr/lib/python3.5/site-packages/peewee.py", line 3500, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/lib/python3.5/site-packages/peewee.py", line 133, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.5/site-packages/peewee.py", line 3586, in connect
    **self.connect_kwargs)
  File "/usr/lib/python3.5/site-packages/peewee.py", line 3855, in _connect
    conn = sqlite3.connect(database, **kwargs)
peewee.OperationalError: unable to open database file
```

**Comment by Seb35** [comment]
Bonjour à vous deux,

Désolé de ne pas avoir répondu, ça fait un bout de temps que je ne me suis pas replongé dans Archéo Lex. Une dynamique est en train de se relancer avec [Légilibre](https://github.com/Legilibre) qui a pour vocation de regrouper les projets sur la thématique de la légistique / droit sur Internet. Je vais transférer Archéo Lex sous cette "organisation".

Concernant vos questions :
@difuse: en regardant [sur la ligne en question](https://github.com/Seb35/Archeo-Lex/blob/master/marcheolex/ranger.py#L46), il faut qu’un certain dossier soit créé, je n’ai peut-être pas mis d’instruction pour le créer s’il n’existe pas. Crée le dossier "bases-xml" dans le sous-dossier "cache" (ie "cache/bases-xml", ça devrait passer outre l’exception. Si c’est bien ça, il faudra que je crée le dossier au lieu d’envoyer une exception.

@hugoroy: je ne sais pas exactement comme ça ; plusieurs possibilités :

* je n’ai pas testé avec Python 3, il est possible qu’il y ait des problèmes
* bien vérifier que le script peut écrire dans le dossier du code (pour y créer les dossiers "cache" qui contiennent les données et les résultats)

À vous deux, avez-vous des projets spécifiques en lien avec le droit ouvert ? Dans tous les cas, n’hésitez pas à rejoindre [les discussions sur Légilibre](https://github.com/Legilibre/salon) (ça commence tout juste, il n’y en pas encore).

**Comment by Seb35** [comment]
Voilà, ce bug à deux têtes est résolu, il s’agissait de répertoires à créer, je les crée au lieu de générer des exceptions. Il y a désormais aussi un vagrantfile permettant d’utiliser Vagrant : crée une machine virtuelle prête à l’emploi pour lancer Archéo Lex (grâce à @promethe42).

**Comment by hugoroy** [comment]
Super; dès que j'ai un peu de temps je teste à nouveau :)

**Comment by tianyikillua** [comment]
Merci tout d'abord tout cet excellent outil mis à disposition.

Comme évoqué dans les commentaires de @difuse, il faut ajouter `Livraison` dans la fonction `initialisation_bdd`, comme ceci :

``` python
for modele in (Livraison, Section, Texte, Version_texte, Version_section, Article):
```

Ensuite, concernant l'erreur qu'avons rencontrée @difuse et moi-même, cela proviendrait peut-être de l'organisation de répertoires pour les XML. En effet, selon `lire_code_xml`, **tous** les fichiers XML devraient se trouver dans `cache/bases-xml/legi/...`, alors que dans `decompresser_base`, les fichiers TAR seront extraits respectivement dans `cache/bases-xml/DATE/[fond,majo]-DATE-*/legi/`, d'où l'erreur.

Est-ce que tout cela provient des commits locaux que vous n'avez pas encore *pushés*...?

Enfin, j'ai donc réorganisé moi-même le répertoire XML en fusionnant tous les `cache/bases-xml/DATE/[fond,majo]-DATE-*/legi/` dans `cache/bases-xml/legi/...`, tout en respectant bien sûr l'ordre chronologique. Néanmoins le fichier Markdown obtenu manque quelques paragraphes dans certaines sections, est-ce normal pour vous ?

Prenons un exemple qui m'intéresse : le [ceseda](https://github.com/tianyikillua/ceseda/blob/master/Code_de_l%E2%80%99entree_et_du_sejour_des_etrangers_et_du_droit_d%E2%80%99asile.md). Le chapitre III est complètement vide après la mise à jour autour du 1er novembre 2016. Il faut travailler dans `ranger.py` concerning les sections j'imagine. J'avoue qu'après quelques heures ce n'est pas encore gagné.

Merci encore une fois.

**Comment by tianyikillua** [comment]
> Enfin, j'ai donc réorganisé moi-même le répertoire XML en fusionnant tous les cache/bases-xml/DATE/[fond,majo]-DATE-*/legi/ dans cache/bases-xml/legi/..., tout en respectant bien sûr l'ordre chronologique. Néanmoins le fichier Markdown obtenu manque quelques paragraphes dans certaines sections, est-ce normal pour vous ?

Problème résolu : les modifications chroniques des sections deviennent trop complexes...

```
LEGISCT1 -> Chapitre I ancien
LEGISCT2 -> Chapitre I nouveau
LEGISCT3 -> Section 1, dont le id_parent est LEGISCT1, mais toujours en vigueur dans la nouvelle version
```

Dans cette configuration, `Section 1` disparaît pour la nouvelle version.

Je n'ai pas encore tout à fait compris, mais le *workaround* que j'ai trouvé est, au lieu de faire

```
articles_section = articles.select().where(Article.version_section == version_section_parente)
```

de prendre maintenant toutes les possibilités

```
articles_section = articles.select().where( (Article.version_section == version_section_parente.cid.cid) | (Article.version_section == version_section_parente))
```

idem pour les sections, dans le fichier `exporter.py`.

Je ferai un pull-request avant 2017 :-)

**Comment by Seb35** [comment]
Je répond rapidement et j’essaye de regarder plus en détails dans la semaine. Dans l’organisation des fichiers intermédiaires, il est possible que j’ai changé des choses en cours de route, et notamment car j’ai essayé à un moment donné d’industrialiser le téléchargement et la gestion de la base LEGI (voir https://github.com/Seb35/loifrancaise, ce que j’appelle "Livraison" = 1 téléchargement quotidien de la base XML). Je regarde donc pour corriger ça en interne à Archéo Lex.

En tous cas ça fait (très) plaisir de voir une réutilisation d’Archéo Lex !
