### ISSUE TITLE
Connecter Archéo Lex avec the-law-factory-parser

### ISSUE THREAD

**Issue by Seb35** [Legilibre/Archeo-Lex#34]
Faire en sorte que Archéo Lex soit compatible avec https://github.com/promethe42/the-law-factory-parser/tree/feature/parse_texte_ast, c’est-à-dire utiliser AL comme source de données de la loi et the-law-factory-parser comme compréhension informatique des amendements ; les deux connectés permettraient de calculer l’application des amendements sur la loi actuelle.

**Comment by Seb35** [comment]
@promethe42 Une proposition de format : https://github.com/Seb35/CIMM-articles, j’ai mis " 1 article = 1 fichier ", ça peut être ajusté si besoin. Je n’ai pas encore publié la version de AL qui a généré ce résultat,  je la publierai prochainement. (J’ai pris le CIMM car il est hyper-court donc rapide à calculer.)

**Comment by JMLX42** [comment]
> CIMM

C'est quel code ?

**Comment by Seb35** [comment]
Code des instruments monétaires et des médailles. C’est surtout pour que tu vois un exemple d’export, je peux en faire tourner d’autres mais ils seront un peu plus long, donc surtout me dire si la forme convient.

**Comment by Seb35** [comment]
Cette issue tombe du fait que c’est plutôt le rôle de _DuraLex, SedLex_ de calculer les projections d’amendements.
