### ISSUE TITLE
Licence Archéo Lex (problème avec la GPL)

### ISSUE THREAD

**Issue by fgallaire** [Legilibre/Archeo-Lex#36]
La licence d'Archéo Lex est censée être la WTFPL.

L'utilisation de `html2text` imposerait une mise en conformité par un passage à la licence GPL, ou a minima l'arrêt immédiat de l'usage de cette bibliothèque.

Cependant, un passge à la GPL pourrait être la meilleure option vu les dépendances souhaitables d'Archéo Lex :
- Git est sous GPL
- Pygit2 est sous GPL
- Mercurial est sous GPL
- Bazaar est sous GPL

**Comment by Seb35** [comment]
La librairie `html2text` est retirée dans 8235494, d’ailleurs elle n’était pas/plus utilisée.
