### ISSUE TITLE
Utilisation de initRechCodeArticle.do

### ISSUE THREAD

**Issue by fgallaire** [Legilibre/Archeo-Lex#38]
L'utilisation de initRechCodeArticle.do est une erreur :
- Le parsing d'un document HTML n'offre aucune garantie
- Ces informations pourraient ne pas être cohérentes avec la base
- Ces informations sont dans la base
- Point de plantage supplémentaire (téléchargement ne marche pas chez moi)

**Comment by Seb35** [comment]
Oui, mais je n’avais pas trouvé d’autre solution à l’époque. Aujourd’hui, avec l’utilisation de legi.py, une grosse partie d’Archéo Lex est désormais inutile (dont le téléchargement dans son entièreté), il faudrait que je supprime ça, ou plus exactement que je tagge ça avec un 0.2 par exemple, puis que je supprime à partir de la version 0.3.

**Comment by Seb35** [comment]
Résolu par le vide : ceci n’est plus utilisé depuis que le téléchargement et la mise en base de données est gérée par legi.py (#31).
