### ISSUE TITLE
fond et majo

### ISSUE THREAD

**Issue by fgallaire** [Legilibre/Archeo-Lex#41]
_fond_ comme diminutif de _fondation_ me semble moins bien que _base_
_majo_ comme diminutif de _mise à jour_ me semble moins bien que _maj_

En tout état de cause, utiliser deux variables permettrait de ne pas avoir à corriger toutes les chaînes de caractères en cas de changement.

**Comment by Seb35** [comment]
J’avais longuement hésité sur les noms, j’avais choisi ceux-là pour que les deux aient 4 lettres pour mieux lire les `ls`, mais je reconnais que ces choix n’étaient pas optimaux. Sur "base", ça peut se comprendre comme "fichier de base", ce qui est bien, mais il y a l’homonyme "base de données" qui était déjà utilisé deux fois en tant que "base de données LEGI en XML" et "base de données SQLite".

De toutes façons, ceci n’est plus d’actualité depuis que le téléchargement est géré par legi.py (#31).
