### ISSUE TITLE
dépôt git avec la constitution

### ISSUE THREAD

**Issue by JMLX42** [Legilibre/Archeo-Lex#46]
Bonjour,

dans le cadre du projet [Amenda](https://framagit.org/parlement-ouvert/amenda/) (une sorte de gitlab pour les projets de loi), nous avons besoin de la constitution (avec son historique) dans un dépôt git.

Possible ?
Comment ?

**Comment by JMLX42** [comment]
Up @Seb35 ?

**Comment by Seb35** [comment]
Désolé de mon absence prolongée, je vais essayer de re-prioriser du temps pour Archéo Lex et autres, ça sera essentiellement sur mes weeks-end.

**Comment by JMLX42** [comment]
La constitution est sur Légifrance :

https://www.legifrance.gouv.fr/Droit-francais/Constitution

Comment en faire un dépôt git avec ArcheoLex ? Merci !

**Comment by Seb35** [comment]
La 5e constitution (et 4e je crois) est aussi et surtout dans un des textes LEGITEXT de la base LEGI. Je te cherche ça tout de suite.

**Comment by Seb35** [comment]
C’est le JORFTEXT000000571356, je l’avais déjà calculé et l’ai transférée sur https://github.com/Assemblee-Citoyenne/constitution-francaise-4-octobre-1958. Il y a aussi les constitutions du 27 octobre 1946 (IVe) et 4 novembre 1848, mais aucune de ces deux dernières n’est complète dans la base LEGI.

**Comment by JMLX42** [comment]
Merci.
Cependant il nous la faudrait avec le formalisme discuté ensemble, à savoir 1 fichier par article.

**Comment by Seb35** [comment]
Je n’ai pas ça sous la main, j’essaye de faire ça cette semaine ou au plus tard ce week-end.

**Comment by JMLX42** [comment]
Ca n'est pas possible de le faire directement avec ArcheoLex?
Il me semble que c'était implémenté.

**Comment by Seb35** [comment]
Bon, voilà, avec le retard, mais c’est fait sur https://github.com/Assemblee-Citoyenne/constitution-francaise-4-octobre-1958 branche "fichiers".

Il n’y a pas le même nombre commits (21 versus 24) que dans la branche master ; je n’ai pas regardé en détails ici mais j’avais déjà observé cela sur d’autres dépôts où il y avait certaines éditions "nulles" (sans changement) et la version "fichier unique" modifie forcément le fichier (au moins la date dans l’introduction), ce qui crée forcément une révision.

**Comment by Seb35** [comment]
La ligne de commande est
```
./archeo-lex --textes=LEGITEXT000006071194 --organisation=repertoires-simple
```
Il y a une subtilité dans les identifiants, le cid est JORFTEXT000000571356, mais l’id est LEGITEXT000006071194.

**Comment by Seb35** [comment]
Si la base LEGI créée par legi.py n’est pas créée (dans cache/sql/legi.sqlite), cela prend du temps, sinon ça prend 5 minutes de calcul.
