### ISSUE TITLE
Mise à jour des données

### ISSUE THREAD

**Issue by juliengossa** [Legilibre/Archeo-Lex#66]
Les dernières données semblent dater d'octobre 2021 pour la plupart des codes. 
Une mise à jour serait-elle possible ?
(Merci pour ce génial projet)

**Comment by Seb35** [comment]
Je viens de voir ton projet https://github.com/juliengossa/legiplot et que effectivement la mise à jour sur archeo-lex.fr s’est arrêtée, je regarde pour la relancer.

**Comment by Seb35** [comment]
C’est en train de tourner.

Le problème était que wget n’arrivait plus à télécharger en FTP depuis le 2021-10-08, peut-être en lien avec le [changement en cours vers FTPS](https://www.data.gouv.fr/fr/datasets/legi-codes-lois-et-reglements-consolides/#discussion-6001b2c2e9f847f01f9e53da), j’ai changé wget en curl qui comprend nativement le type de FTP que la DILA utilise.

**Comment by juliengossa** [comment]
Après contact avec la DILA, ça venait effectivement de la migration FTP
vers FTPS.
Je n'ai pas eu le temps de proposer un patch, donc merci beaucoup de
l'avoir fait !
Et bravo pour le projet, c'est précieux.

Le jeu. 24 mars 2022 à 13:08, Sébastien Beyou ***@***.***> a
écrit :

**Comment by Seb35** [comment]
C’est terminé pour la màj au 23 mars 2022 et bientôt fini pour le 24 mars 2022, c’est donc bien reparti.

Si besoin de compléments, je suis dispo et il y a aussi le [salon](https://github.com/Legilibre/salon/issues) qui sert de forum avec quelques autres légisticiens. Je n’ai pas encore regardé en détails legiplot mais je regarde sous peu. En tous cas, je suis heureux que Archéo Lex ait servi à d’autres projets :)
